### ISSUE TITLE
Missing git tag for 8.3.0

### ISSUE THREAD

**Issue by MatheusMoura17** [GameWorkstore/com.google.firebase.firestore#1]
@john-rosa-playkids you are commited  `8.3.0` https://github.com/GameWorkstore/com.google.firebase.firestore/commit/fb987401d5ca842c49b5b49bdee4d3620da87ccf of firestore in `master` branch, but forgot the release in git hub tags. 

tks for this repo!

**Comment by HanzaRu** [comment]
Hi, @MatheusMoura17, it's fixed now!
thanks for point out!
You can test and if you don't find any other thing, can close this issue?

Kind Regards,
John

**Comment by MatheusMoura17** [comment]
Works fine!
